apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    k8s-app: fluent-bit
data:
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Merge_Log_Trim On
        Labels On
        Annotations Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
    
    [FILTER]
        Name grep
        Match kube.*
        Exclude $kubernetes['namespace_name'] kube-system
        Exclude $kubernetes['namespace_name'] kube-public
        Exclude $kubernetes['namespace_name'] kube-node-lease
        Exclude $kubernetes['namespace_name'] ingress-nginx

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix kubernetes_

    [FILTER]
        Name modify
        Match kube.*
        Rename log content
        Remove kubernetes_docker_id
        Remove kubernetes_container_name
        Remove kubernetes_container_hash
        Remove kubernetes_container_image

    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-logging
        Port            9200
        Generate_ID on
        